name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        freebsd-version: ['14.1', '14.0', '13.3', '13.2']

    steps:
      - uses: actions/checkout@v4

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: freebsd
          version: ${{ matrix.freebsd-version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run sudo pkg update
            run sudo pkg install -y cmake ninja gcc pkgconf curl openssl libgit2 libarchive libyaml jansson sqlite3 libnghttp2

            run cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
            run cmake --build   build.d
            run cmake --install build.d

            run ./output/bin/uppm

            run ./output/bin/uppm --help
            run ./output/bin/uppm --version

            run ./output/bin/uppm -h
            run ./output/bin/uppm -V

            run ./output/bin/uppm about
            run ./output/bin/uppm about -v

            run ./output/bin/uppm integrate zsh

            run ./output/bin/uppm update

            run ./output/bin/uppm search zip

            run ./output/bin/uppm depends gzip

            run ./output/bin/uppm info-available gsed
            run ./output/bin/uppm info-available gsed --json
            run ./output/bin/uppm info-available gsed --yaml
            run ./output/bin/uppm info-available gsed version
            run ./output/bin/uppm info-available gsed license
            run ./output/bin/uppm info-available gsed summary
            run ./output/bin/uppm info-available gsed webpage
            run ./output/bin/uppm info-available gsed bin-url
            run ./output/bin/uppm info-available gsed bin-sha
            run ./output/bin/uppm info-available gsed install
            run ./output/bin/uppm info-available gsed formula

            run ./output/bin/uppm fetch   gzip
            run ./output/bin/uppm fetch   gtar -v

            run ./output/bin/uppm install gsed

            run ./output/bin/uppm info-installed gsed --files
            run ./output/bin/uppm info-installed gsed --json
            run ./output/bin/uppm info-installed gsed --yaml
            run ./output/bin/uppm info-installed gsed timestamp-unix
            run ./output/bin/uppm info-installed gsed timestamp-iso-8601
            run ./output/bin/uppm info-installed gsed timestamp-rfc-3339
            run ./output/bin/uppm info-installed gsed version

            run ./output/bin/uppm tree gsed
            run ./output/bin/uppm tree gsed -L 3

            printf '%s\n' 'version: 1000' >> ~/.uppm/repos.d/official-core/formula/gsed.yml

            run ./output/bin/uppm ls-available
            run ./output/bin/uppm ls-installed
            run ./output/bin/uppm ls-outdated

            run ./output/bin/uppm is-available curl
            run ./output/bin/uppm is-installed gsed
            run ./output/bin/uppm is-outdated  gsed || echo not outdated

            run ./output/bin/uppm upgrade   gsed
            run ./output/bin/uppm reinstall gsed
            run ./output/bin/uppm uninstall gsed


            run ./output/bin/uppm formula-repo-list
            run ./output/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
            run ./output/bin/uppm formula-repo-del my_repo

            run ./output/bin/uppm cleanup

