name: macos

on:
  push:
    branches: [ 0.15.4 ]
  pull_request:
    branches: [ 0.15.4 ]

jobs:

  brew:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main

      - run:  brew update
      - run:  brew install --overwrite python@3.10 python@3.11
      - run:  brew install cmake ninja pkg-config curl sqlite jansson libyaml libgit2 libarchive

      - run: sed -i '.bak' '/Requires.private:/d' "$(brew --prefix libarchive)/lib/pkgconfig/libarchive.pc"

      - run:  |
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig"
          CMAKE_EXE_LINKER_FLAGS='-L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -lssl -liconv -framework CoreFoundation -framework Security'
          CMAKE_FIND_ROOT_PATH="$(brew --prefix openssl@1.1);$(brew --prefix curl);$(brew --prefix sqlite);$(brew --prefix libarchive)"

          cmake \
              -S . \
              -B build.d \
              -G Ninja \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DCMAKE_EXE_LINKER_FLAGS="$CMAKE_EXE_LINKER_FLAGS" \
              -DCMAKE_FIND_ROOT_PATH="$CMAKE_FIND_ROOT_PATH"

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run:  ./output/bin/uppm

      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version

      - run:  ./output/bin/uppm -h
      - run:  ./output/bin/uppm -V

      - run:  ./output/bin/uppm about
      - run:  ./output/bin/uppm about -v

      - run:  ./output/bin/uppm integrate zsh -v

      - run:  ./output/bin/uppm update

      - run:  ./output/bin/uppm search zip

      - run:  ./output/bin/uppm depends zip
      - run:  ./output/bin/uppm depends android-sdk
      - run:  ./output/bin/uppm depends android-sdk -t box
      - run:  ./output/bin/uppm depends android-sdk -t dot

      - run:  ./output/bin/uppm info @all
      - run:  ./output/bin/uppm info gsed
      - run:  ./output/bin/uppm info gsed --json
      - run:  ./output/bin/uppm info gsed --yaml
      - run:  ./output/bin/uppm info gsed version
      - run:  ./output/bin/uppm info gsed license
      - run:  ./output/bin/uppm info gsed summary
      - run:  ./output/bin/uppm info gsed webpage
      - run:  ./output/bin/uppm info gsed bin-url
      - run:  ./output/bin/uppm info gsed bin-sha
      - run:  ./output/bin/uppm info gsed install
      - run:  ./output/bin/uppm info gsed formula

      - run:  ./output/bin/uppm fetch   gzip
      - run:  ./output/bin/uppm fetch   gtar -v

      - run:  ./output/bin/uppm install gsed

      - run:  ./output/bin/uppm info gsed installed-dir
      - run:  ./output/bin/uppm info gsed installed-files
      - run:  ./output/bin/uppm info gsed installed-receipt-path
      - run:  ./output/bin/uppm info gsed installed-receipt-json
      - run:  ./output/bin/uppm info gsed installed-receipt-yaml
      - run:  ./output/bin/uppm info gsed installed-timestamp-unix
      - run:  ./output/bin/uppm info gsed installed-timestamp-iso-8601
      - run:  ./output/bin/uppm info gsed installed-timestamp-rfc-3339
      - run:  ./output/bin/uppm info gsed installed-version

      - run:  ./output/bin/uppm tree gsed
      - run:  ./output/bin/uppm tree gsed -L 3

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.uppm/repos.d/official-core/formula/gsed.yml

      - run:  ./output/bin/uppm ls-available
      - run:  ./output/bin/uppm ls-installed
      - run:  ./output/bin/uppm ls-outdated

      - run:  ./output/bin/uppm is-available curl
      - run:  ./output/bin/uppm is-installed gsed
      - run:  ./output/bin/uppm is-outdated  gsed

      - run:  ./output/bin/uppm upgrade   gsed
      - run:  ./output/bin/uppm reinstall gsed
      - run:  ./output/bin/uppm uninstall gsed


      - run:  ./output/bin/uppm formula-repo-list
      - run:  ./output/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
      - run:  ./output/bin/uppm formula-repo-del my_repo

      - run:  ./output/bin/uppm cleanup

  vcpkg:

    strategy:
      fail-fast: false
      matrix:
        version: [macos-11, macos-12]

    runs-on: ${{ matrix.version }}

    steps:
      - run:  brew update
      - run:  brew install cmake ninja pkg-config

      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - run:  cd vcpkg && ./bootstrap-vcpkg.sh

      - run:  cd vcpkg && ./vcpkg install curl openssl libgit2 libarchive libyaml jansson sqlite3

      - run:  |
          cmake \
              -S . \
              -B build.d \
              -G Ninja \
              -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run:  ./output/bin/uppm

      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version

      - run:  ./output/bin/uppm -h
      - run:  ./output/bin/uppm -V

      - run:  ./output/bin/uppm about
      - run:  ./output/bin/uppm about -v

      - run:  ./output/bin/uppm integrate zsh -v

      - run:  ./output/bin/uppm update

      - run:  ./output/bin/uppm search zip

      - run:  ./output/bin/uppm depends zip
      - run:  ./output/bin/uppm depends android-sdk
      - run:  ./output/bin/uppm depends android-sdk -t box
      - run:  ./output/bin/uppm depends android-sdk -t dot

      - run:  ./output/bin/uppm info @all
      - run:  ./output/bin/uppm info gsed
      - run:  ./output/bin/uppm info gsed --json
      - run:  ./output/bin/uppm info gsed --yaml
      - run:  ./output/bin/uppm info gsed version
      - run:  ./output/bin/uppm info gsed license
      - run:  ./output/bin/uppm info gsed summary
      - run:  ./output/bin/uppm info gsed webpage
      - run:  ./output/bin/uppm info gsed bin-url
      - run:  ./output/bin/uppm info gsed bin-sha
      - run:  ./output/bin/uppm info gsed install
      - run:  ./output/bin/uppm info gsed formula

      - run:  ./output/bin/uppm fetch   gzip
      - run:  ./output/bin/uppm fetch   gtar -v

      - run:  ./output/bin/uppm install gsed

      - run:  ./output/bin/uppm info gsed installed-dir
      - run:  ./output/bin/uppm info gsed installed-files
      - run:  ./output/bin/uppm info gsed installed-receipt-path
      - run:  ./output/bin/uppm info gsed installed-receipt-json
      - run:  ./output/bin/uppm info gsed installed-receipt-yaml
      - run:  ./output/bin/uppm info gsed installed-timestamp-unix
      - run:  ./output/bin/uppm info gsed installed-timestamp-iso-8601
      - run:  ./output/bin/uppm info gsed installed-timestamp-rfc-3339
      - run:  ./output/bin/uppm info gsed installed-version

      - run:  ./output/bin/uppm tree gsed
      - run:  ./output/bin/uppm tree gsed -L 3

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.uppm/repos.d/official-core/formula/gsed.yml

      - run:  ./output/bin/uppm ls-available
      - run:  ./output/bin/uppm ls-installed
      - run:  ./output/bin/uppm ls-outdated

      - run:  ./output/bin/uppm is-available curl
      - run:  ./output/bin/uppm is-installed gsed
      - run:  ./output/bin/uppm is-outdated  gsed

      - run:  ./output/bin/uppm upgrade   gsed
      - run:  ./output/bin/uppm reinstall gsed
      - run:  ./output/bin/uppm uninstall gsed


      - run:  ./output/bin/uppm formula-repo-list
      - run:  ./output/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
      - run:  ./output/bin/uppm formula-repo-del my_repo

      - run:  ./output/bin/uppm cleanup

  vcpkg-sanitizer:

    strategy:
      fail-fast: false
      matrix:
        version: [macos-11, macos-12]

    runs-on: ${{ matrix.version }}

    steps:
      - run:  brew update
      - run:  brew install --overwrite python@3.10 python@3.11
      - run:  brew install cmake ninja llvm pkg-config

      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - run:  cd vcpkg && ./bootstrap-vcpkg.sh

      - run:  cd vcpkg && ./vcpkg install curl openssl libgit2 libarchive libyaml jansson sqlite3

      - run:  |
          cmake \
              -S . \
              -B build.d \
              -G Ninja \
              -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang \
              -DCMAKE_C_FLAGS="-fsanitize=undefined -fsanitize=address -fsanitize=leak"

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run:  ./output/bin/uppm

      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version

      - run:  ./output/bin/uppm -h
      - run:  ./output/bin/uppm -V

      - run:  ./output/bin/uppm about
      - run:  ./output/bin/uppm about -v

      - run:  ./output/bin/uppm integrate zsh -v

      - run:  ./output/bin/uppm update

      - run:  ./output/bin/uppm search zip

      - run:  ./output/bin/uppm depends zip
      - run:  ./output/bin/uppm depends android-sdk
      - run:  ./output/bin/uppm depends android-sdk -t box
      - run:  ./output/bin/uppm depends android-sdk -t dot

      - run:  ./output/bin/uppm info @all
      - run:  ./output/bin/uppm info gsed
      - run:  ./output/bin/uppm info gsed --json
      - run:  ./output/bin/uppm info gsed --yaml
      - run:  ./output/bin/uppm info gsed version
      - run:  ./output/bin/uppm info gsed license
      - run:  ./output/bin/uppm info gsed summary
      - run:  ./output/bin/uppm info gsed webpage
      - run:  ./output/bin/uppm info gsed bin-url
      - run:  ./output/bin/uppm info gsed bin-sha
      - run:  ./output/bin/uppm info gsed install
      - run:  ./output/bin/uppm info gsed formula

      - run:  ./output/bin/uppm fetch   gzip
      - run:  ./output/bin/uppm fetch   gtar -v

      - run:  ./output/bin/uppm install gsed

      - run:  ./output/bin/uppm info gsed installed-dir
      - run:  ./output/bin/uppm info gsed installed-files
      - run:  ./output/bin/uppm info gsed installed-receipt-path
      - run:  ./output/bin/uppm info gsed installed-receipt-json
      - run:  ./output/bin/uppm info gsed installed-receipt-yaml
      - run:  ./output/bin/uppm info gsed installed-timestamp-unix
      - run:  ./output/bin/uppm info gsed installed-timestamp-iso-8601
      - run:  ./output/bin/uppm info gsed installed-timestamp-rfc-3339
      - run:  ./output/bin/uppm info gsed installed-version

      - run:  ./output/bin/uppm tree gsed
      - run:  ./output/bin/uppm tree gsed -L 3

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.uppm/repos.d/official-core/formula/gsed.yml

      - run:  ./output/bin/uppm ls-available
      - run:  ./output/bin/uppm ls-installed
      - run:  ./output/bin/uppm ls-outdated

      - run:  ./output/bin/uppm is-available curl
      - run:  ./output/bin/uppm is-installed gsed
      - run:  ./output/bin/uppm is-outdated  gsed

      - run:  ./output/bin/uppm upgrade   gsed
      - run:  ./output/bin/uppm reinstall gsed
      - run:  ./output/bin/uppm uninstall gsed


      - run:  ./output/bin/uppm formula-repo-list
      - run:  ./output/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
      - run:  ./output/bin/uppm formula-repo-del my_repo

      - run:  ./output/bin/uppm cleanup

  brew-sanitizer:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main

      - run:  brew update
      - run:  brew install --overwrite python@3.10 python@3.11
      - run:  brew install cmake ninja llvm pkg-config curl sqlite jansson libyaml libgit2 libarchive

      - run: sed -i '.bak' '/Requires.private:/d' "$(brew --prefix libarchive)/lib/pkgconfig/libarchive.pc"

      - run:  |
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig"
          CMAKE_EXE_LINKER_FLAGS='-L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -lssl -liconv -framework CoreFoundation -framework Security'
          CMAKE_FIND_ROOT_PATH="$(brew --prefix openssl@1.1);$(brew --prefix curl);$(brew --prefix sqlite);$(brew --prefix libarchive)"

          cmake \
              -S . \
              -B build.d \
              -G Ninja \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DCMAKE_EXE_LINKER_FLAGS="$CMAKE_EXE_LINKER_FLAGS" \
              -DCMAKE_FIND_ROOT_PATH="$CMAKE_FIND_ROOT_PATH" \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang \
              -DCMAKE_C_FLAGS="-fsanitize=undefined -fsanitize=address -fsanitize=leak"

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run:  ./output/bin/uppm

      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version

      - run:  ./output/bin/uppm -h
      - run:  ./output/bin/uppm -V

      - run:  ./output/bin/uppm about
      - run:  ./output/bin/uppm about -v

      - run:  ./output/bin/uppm integrate zsh -v

      - run:  ./output/bin/uppm update

      - run:  ./output/bin/uppm search zip

      - run:  ./output/bin/uppm depends zip
      - run:  ./output/bin/uppm depends android-sdk
      - run:  ./output/bin/uppm depends android-sdk -t box
      - run:  ./output/bin/uppm depends android-sdk -t dot

      - run:  ./output/bin/uppm info @all
      - run:  ./output/bin/uppm info gsed
      - run:  ./output/bin/uppm info gsed --json
      - run:  ./output/bin/uppm info gsed --yaml
      - run:  ./output/bin/uppm info gsed version
      - run:  ./output/bin/uppm info gsed license
      - run:  ./output/bin/uppm info gsed summary
      - run:  ./output/bin/uppm info gsed webpage
      - run:  ./output/bin/uppm info gsed bin-url
      - run:  ./output/bin/uppm info gsed bin-sha
      - run:  ./output/bin/uppm info gsed install
      - run:  ./output/bin/uppm info gsed formula

      - run:  ./output/bin/uppm fetch   gzip
      - run:  ./output/bin/uppm fetch   gtar -v

      - run:  ./output/bin/uppm install gsed

      - run:  ./output/bin/uppm info gsed installed-dir
      - run:  ./output/bin/uppm info gsed installed-files
      - run:  ./output/bin/uppm info gsed installed-receipt-path
      - run:  ./output/bin/uppm info gsed installed-receipt-json
      - run:  ./output/bin/uppm info gsed installed-receipt-yaml
      - run:  ./output/bin/uppm info gsed installed-timestamp-unix
      - run:  ./output/bin/uppm info gsed installed-timestamp-iso-8601
      - run:  ./output/bin/uppm info gsed installed-timestamp-rfc-3339
      - run:  ./output/bin/uppm info gsed installed-version

      - run:  ./output/bin/uppm tree gsed
      - run:  ./output/bin/uppm tree gsed -L 3

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.uppm/repos.d/official-core/formula/gsed.yml

      - run:  ./output/bin/uppm ls-available
      - run:  ./output/bin/uppm ls-installed
      - run:  ./output/bin/uppm ls-outdated

      - run:  ./output/bin/uppm is-available curl
      - run:  ./output/bin/uppm is-installed gsed
      - run:  ./output/bin/uppm is-outdated  gsed

      - run:  ./output/bin/uppm upgrade   gsed
      - run:  ./output/bin/uppm reinstall gsed
      - run:  ./output/bin/uppm uninstall gsed


      - run:  ./output/bin/uppm formula-repo-list
      - run:  ./output/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
      - run:  ./output/bin/uppm formula-repo-del my_repo

      - run:  ./output/bin/uppm cleanup
