name: openSUSE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  opensuse:
    strategy:
      fail-fast: false
      matrix:
        flavor: ['tumbleweed', 'leap:15.4']

    runs-on: ubuntu-latest

    container: opensuse/${{ matrix.flavor }}

    steps:
      - run: zypper update  -y
      - run: zypper install -y git cmake ninja gcc pkg-config libcurl-devel libgit2-devel libarchive-devel libyaml-devel libjansson-devel sqlite3-devel

      - uses: actions/checkout@main

      - run:  cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run:  ./output/bin/uppm

      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version

      - run:  ./output/bin/uppm -h
      - run:  ./output/bin/uppm -V

      - run:  ./output/bin/uppm about
      - run:  ./output/bin/uppm about -v

      - run:  ./output/bin/uppm integrate zsh

      - run:  ./output/bin/uppm update

      - run:  ./output/bin/uppm search zip

      - run:  ./output/bin/uppm depends zip
      - run:  ./output/bin/uppm depends android-sdk
      - run:  ./output/bin/uppm depends android-sdk -t box
      - run:  ./output/bin/uppm depends android-sdk -t dot

      - run:  ./output/bin/uppm info-available unzip
      - run:  ./output/bin/uppm info-available unzip --json
      - run:  ./output/bin/uppm info-available unzip --yaml
      - run:  ./output/bin/uppm info-available unzip version
      - run:  ./output/bin/uppm info-available unzip license
      - run:  ./output/bin/uppm info-available unzip summary
      - run:  ./output/bin/uppm info-available unzip webpage
      - run:  ./output/bin/uppm info-available unzip bin-url
      - run:  ./output/bin/uppm info-available unzip bin-sha
      - run:  ./output/bin/uppm info-available unzip install
      - run:  ./output/bin/uppm info-available unzip formula

      - run:  ./output/bin/uppm fetch   gzip
      - run:  ./output/bin/uppm fetch   gsed -v

      - run:  ./output/bin/uppm install unzip

      - run:  ./output/bin/uppm info-installed unzip --prefix
      - run:  ./output/bin/uppm info-installed unzip --files
      - run:  ./output/bin/uppm info-installed unzip --json
      - run:  ./output/bin/uppm info-installed unzip --yaml
      - run:  ./output/bin/uppm info-installed unzip timestamp-unix
      - run:  ./output/bin/uppm info-installed unzip timestamp-iso-8601
      - run:  ./output/bin/uppm info-installed unzip timestamp-rfc-3339
      - run:  ./output/bin/uppm info-installed unzip version

      - run:  ./output/bin/uppm tree unzip
      - run:  ./output/bin/uppm tree unzip -L 3

      - run: |
          sed -i '/^version: /c version: 1000' $(./output/bin/uppm info-available unzip formula)

      - run:  ./output/bin/uppm ls-available
      - run:  ./output/bin/uppm ls-installed
      - run:  ./output/bin/uppm ls-outdated

      - run:  ./output/bin/uppm is-available curl
      - run:  ./output/bin/uppm is-installed unzip
      - run:  ./output/bin/uppm is-outdated  unzip || echo not outdated

      - run:  ./output/bin/uppm upgrade   unzip
      - run:  ./output/bin/uppm reinstall unzip
      - run:  ./output/bin/uppm uninstall unzip


      - run:  ./output/bin/uppm formula-repo-list
      - run:  ./output/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
      - run:  ./output/bin/uppm formula-repo-del my_repo

      - run:  ./output/bin/uppm cleanup
