name: ppkg

on:
  push:
    branches: [ 0.15.4 ]
  pull_request:
    branches: [ 0.15.4 ]

jobs:
  ppkg:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, ubuntu-22.04, ubuntu-24.04, macos-14, macos-15, macos-26]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main


      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - run: ./ppkg setup
      - run: ./ppkg update

      - run: |
          echo "src-url: dir://$PWD" >> ~/.ppkg/repos.d/official-core/formula/uppm.yml

      - run: ./ppkg install uppm
      - run: ./ppkg bundle  uppm .tar.gz

      - run: tar xvf *.tar.gz --strip-components=1

      - run:  echo "SSL_CERT_FILE=$HOME/.ppkg/core/cacert.pem" >> $GITHUB_ENV


      - run:  bin/uppm

      - run:  bin/uppm --help
      - run:  bin/uppm --version

      - run:  bin/uppm -h
      - run:  bin/uppm -V

      - run:  bin/uppm about
      - run:  bin/uppm about -v

      - run:  bin/uppm sysinfo

      - run:  bin/uppm integrate zsh

      - run:  bin/uppm update

      - run:  bin/uppm search zip

      - run:  bin/uppm depends zip
      - run:  bin/uppm depends android-sdk
      - run:  bin/uppm depends android-sdk -t box
      - run:  bin/uppm depends android-sdk -t dot

      - run:  bin/uppm info @all
      - run:  bin/uppm info gsed
      - run:  bin/uppm info gsed --json
      - run:  bin/uppm info gsed --yaml
      - run:  bin/uppm info gsed version
      - run:  bin/uppm info gsed license
      - run:  bin/uppm info gsed summary
      - run:  bin/uppm info gsed webpage
      - run:  bin/uppm info gsed bin-url
      - run:  bin/uppm info gsed bin-sha
      - run:  bin/uppm info gsed install
      - run:  bin/uppm info gsed formula

      - run:  bin/uppm fetch   gtar
      - run:  bin/uppm fetch   gtar -v

      - run:  bin/uppm install gsed

      - run:  bin/uppm info gsed installed-dir
      - run:  bin/uppm info gsed --files
      - run:  bin/uppm info gsed installed-receipt-path
      - run:  bin/uppm info gsed installed-receipt-json
      - run:  bin/uppm info gsed installed-receipt-yaml
      - run:  bin/uppm info gsed installed-timestamp-unix
      - run:  bin/uppm info gsed installed-timestamp-iso-8601
      - run:  bin/uppm info gsed installed-timestamp-rfc-3339
      - run:  bin/uppm info gsed installed-version

      - run:  bin/uppm tree gsed
      - run:  bin/uppm tree gsed -L 3

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.uppm/repos.d/official-core/formula/gsed.yml

      - run:  bin/uppm ls-available
      - run:  bin/uppm ls-installed
      - run:  bin/uppm ls-outdated

      - run:  bin/uppm is-available curl
      - run:  bin/uppm is-installed gsed
      - run:  bin/uppm is-outdated  gsed

      - run:  bin/uppm upgrade   gsed
      - run:  bin/uppm reinstall gsed
      - run:  bin/uppm uninstall gsed


      - run:  bin/uppm formula-repo-list
      - run:  bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
      - run:  bin/uppm formula-repo-del my_repo

      - run:  bin/uppm cleanup
