name: Rocky Linux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['8', '9']

    container: rockylinux:${{ matrix.tag }}

    steps:
      - run:  dnf -y update
      - run:  dnf -y install xz gcc-c++
      - run:  |
          command -v curl > /dev/null || dnf -y install curl
          # https://bugs.launchpad.net/tripleo/+bug/1953156

      - uses: actions/checkout@main

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install uppm
      - run:  ./ppkg tree    uppm



      - run:  echo "SSL_CERT_FILE=$HOME/.ppkg/core/cacert.pem" >> $GITHUB_ENV


      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm --help
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm --version

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm -h
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm -V

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm env
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm env -v

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm integrate zsh

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm update

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm search zip

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm depends zip
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm depends android-sdk
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm depends android-sdk -t box
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm depends android-sdk -t dot

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip --json
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip --yaml
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip version
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip license
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip summary
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip webpage
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip bin-url
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip bin-sha
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip install
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip formula

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm fetch   gzip
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm fetch   gsed -v

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm install unzip

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-installed unzip --prefix
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-installed unzip --files
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-installed unzip --json
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-installed unzip --yaml
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-installed unzip timestamp-unix
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-installed unzip timestamp-iso-8601
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-installed unzip timestamp-rfc-3339
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-installed unzip version

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm tree unzip
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm tree unzip -L 3

      - run: |
          sed -i '/^version: /c version: 1000' $(~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm info-available unzip formula)

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm ls-available
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm ls-installed
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm ls-outdated

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm is-available curl
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm is-installed unzip
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm is-outdated  unzip || echo not outdated

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm upgrade   unzip
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm reinstall unzip
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm uninstall unzip


      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm formula-repo-list
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm formula-repo-del my_repo

      - run:  ~/.ppkg/installed/linux-glibc-x86_64/uppm/bin/uppm cleanup
