name: voidlinux

on:
  push:
    branches: [ 0.15.4 ]
  pull_request:
    branches: [ 0.15.4 ]

jobs:
  voidlinux:
    strategy:
      fail-fast: false
      matrix:
        variant: ['voidlinux', 'voidlinux-musl']

    runs-on: ubuntu-latest

    container: voidlinux/${{ matrix.variant }}

    steps:
      # SSL certificate subject doesn't match host alpha.de.repo.voidlinux.org
      # ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata': Operation not permitted
      - run: sed -i s/alpha.de.repo.voidlinux.org/repo-default.voidlinux.org/g /usr/share/xbps.d/*

      - run: xbps-install -Suy xbps
      - run: xbps-install -Suy ca-certificates
      - run: xbps-install -Suy cmake ninja gcc pkg-config libcurl-devel libgit2-devel libarchive-devel libyaml-devel jansson-devel sqlite-devel

      # https://github.com/actions/checkout/issues/334
      - uses: actions/checkout@v1


      - run:  cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run:  ./output/bin/uppm

      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version

      - run:  ./output/bin/uppm -h
      - run:  ./output/bin/uppm -V

      - run:  ./output/bin/uppm about
      - run:  ./output/bin/uppm about -v

      - run:  ./output/bin/uppm integrate zsh

      - run:  ./output/bin/uppm update

      - run:  ./output/bin/uppm search zip

      - run:  ./output/bin/uppm depends zip
      - run:  ./output/bin/uppm depends android-sdk
      - run:  ./output/bin/uppm depends android-sdk -t box
      - run:  ./output/bin/uppm depends android-sdk -t dot

      - run:  ./output/bin/uppm info @all
      - run:  ./output/bin/uppm info unzip
      - run:  ./output/bin/uppm info unzip --json
      - run:  ./output/bin/uppm info unzip --yaml
      - run:  ./output/bin/uppm info unzip version
      - run:  ./output/bin/uppm info unzip license
      - run:  ./output/bin/uppm info unzip summary
      - run:  ./output/bin/uppm info unzip webpage
      - run:  ./output/bin/uppm info unzip bin-url
      - run:  ./output/bin/uppm info unzip bin-sha
      - run:  ./output/bin/uppm info unzip install
      - run:  ./output/bin/uppm info unzip formula

      - run:  ./output/bin/uppm fetch   gzip
      - run:  ./output/bin/uppm fetch   gsed -v

      - run:  ./output/bin/uppm install unzip

      - run:  ./output/bin/uppm info unzip installed-dir
      - run:  ./output/bin/uppm info unzip installed-files
      - run:  ./output/bin/uppm info unzip installed-receipt-path
      - run:  ./output/bin/uppm info unzip installed-receipt-json
      - run:  ./output/bin/uppm info unzip installed-receipt-yaml
      - run:  ./output/bin/uppm info unzip installed-timestamp-unix
      - run:  ./output/bin/uppm info unzip installed-timestamp-iso-8601
      - run:  ./output/bin/uppm info unzip installed-timestamp-rfc-3339
      - run:  ./output/bin/uppm info unzip installed-version

      - run:  ./output/bin/uppm tree unzip
      - run:  ./output/bin/uppm tree unzip -L 3

      - run: |
          sed -i '/^version: /c version: 1000' $(./output/bin/uppm info unzip formula | head -n 1 | cut -d ' ' -f2)

      - run:  ./output/bin/uppm ls-available
      - run:  ./output/bin/uppm ls-installed
      - run:  ./output/bin/uppm ls-outdated

      - run:  ./output/bin/uppm is-available curl
      - run:  ./output/bin/uppm is-installed unzip
      - run:  ./output/bin/uppm is-outdated  unzip

      - run:  ./output/bin/uppm upgrade   unzip
      - run:  ./output/bin/uppm reinstall unzip
      - run:  ./output/bin/uppm uninstall unzip


      - run:  ./output/bin/uppm formula-repo-list
      - run:  ./output/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
      - run:  ./output/bin/uppm formula-repo-del my_repo

      - run:  ./output/bin/uppm cleanup

